apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: moon-retain
  namespace: moon
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: moon-retainer
reclaimPolicy: Retain # default value is Delete
 